version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader123
      POSTGRES_DB: trading_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://trader:trader123@postgres:5432/trading_bot_db
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./src:/app/src
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  postgres_data: