services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

  backend:
    environment:
      - DEBUG=true
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"

  frontend:
    environment:
      - DEBUG=true
    volumes:
      - ./src:/app/src
    ports:
      - "8501:8501"