name: ${COMPOSE_PROJECT_NAME:-trading_bot}
services:
  postgres:
    container_name: ${PROJECT_NAME:-trading_bot}_postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: ${PROJECT_NAME:-trading_bot}_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    container_name: ${PROJECT_NAME:-trading_bot}_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./src:/app/src
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0


volumes:
  postgres_data: